### ISSUE TITLE
Headers added to request via .NET addin are not received on the API server

### ISSUE THREAD

**Issue by avonplato** [RickStrahl/WestWindWebSurge#101]
Hi Team,

We have been testing websurge, specifically the addins process, in the hope it will solve a stress test use case for us. If it does, we will buy licenses.

Our problem is that when intercepting the request and attaching our own headers (Authorization and 1 customer) these headers are not received on the server.

Oddly though, if i take the headers from the preview window and insert them into the http request tab and try again, it works as expected.

Is there a bug or are we using the tool incorrectly.

Thanks

**Comment by RickStrahl** [comment]
That sounds like a bug... 

There's been a lot of work in the HTTP engine and I suspect the `OnBeforeRequestSent()` event is perhaps getting fired too late after the request has already been assigned to the HTTP client. I'll take a look.

**Comment by RickStrahl** [comment]
Give this a try with 2.1.7.3.

As suspected the timing of the event was too late to affect the headers already added to the Http client. The event now fires a little earlier in the sequence before content and headers are assigned.
