### ISSUE TITLE
Request: Header instead of websurge-allow.txt/robots.txt

### ISSUE THREAD

**Issue by ope-nz** [RickStrahl/WestWindWebSurge#103]
Hi there, I totally understand the need to these checks before running a test. However with some modern enterprise stacks eg kubernetes it is difficult to implement these options when you dont have access to the backend.

As an example Im trying to run tests against a COTS web service application that runs on a kubernetes cluster. There is no access to the web server itself (which runs in a pod). Luckily it sits behind Azure Front Door so I have been able to set up a redirect for websurge-allow.txt and this works.

However it would be good if there was another option to allow testing e.g. via a response header.

Appending a header is much easier to implement via a WAF, CDN, load balancer etc.

Maybe a header like this; WebSurge: Allow

**Comment by RickStrahl** [comment]
If you don't own the service you can't run the tests. You have to be able to prove that you have access to the service in order to test against it. You can add a file or if it's some other tooling that can't do files you can probably use a custom route to force it, but you need to be able to control that content to 'validate' that you can access it at the given domain/ip.

**Comment by ope-nz** [comment]
Thanks Rick, totally understand the requirement.

In this case I do have access to the management of the WAF & infrastructure in the Azure portal but as its a COTS docker/kubernetes based application there is no accessible web server. Its all preconfigured by the vendor and there is no static file location to drop files into.

As mentioned I can work around it (becuase I have access in the Azure portal) but its a bit of a hacky work around.

I didnt realise you'd need to check the headers each time, so that obviously wont work.

**Comment by RickStrahl** [comment]
Actually I lied :smile: (well I didn't think this through). The way WS checks is by running a pre-test against each site url that is in the session and then checks for the required files.

The problem with headers is that we wouldn't know what Url to check for the headers. I suppose we could say that it has to be on the site root url `/` (kind of like Google does with meta headers) - that would work. On your end you can then add the header into the Web Server headers, but you'd end up with the header on every page which adds overhead. Not sure if this would a be good solution. Personally I don't like it, but I see how this would be easier for services where you can modify headers but can't easily add files or urls.
