### ISSUE TITLE
Bug? SiteBaseUrl not set from session file

### ISSUE THREAD

**Issue by ope-nz** [RickStrahl/WestWindWebSurge#104]
I have a session file with SiteBaseUrl set in the WebSurge Options.

If I close WebSurge and double click the websurge file the Site Base Url is not set.

File contents

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/0b9ded29-61a5-4146-8506-05adc6f0ad7b)

When I open the session file the Site Base Url is not set.
![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/018f47c8-d4c2-42e4-99f1-b6d790cf2966)

The recents list is populated though...

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/2824c897-54ff-4170-b70e-6c56aa2386d7)

**Comment by ope-nz** [comment]
To add to this; If I open different session and then swap to one that has SiteBaseUrl set then it is correctly populated.

**Comment by RickStrahl** [comment]
I've seen this on occasion, but I can't reliably reproduce it. I'll take another look.

**Comment by ope-nz** [comment]
Another observation, even though the UI doesnt show the base URL it does appear to pick it up regardless (and I have no problems using the CLI too).

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/7f1936f7-7d48-4fb1-b4ea-3236faeb6ca3)

**Comment by RickStrahl** [comment]
Fixed some time ago.

We did have a logic bug with the multi-select box not properly binding the value. That's been fixed with some explicit code updates.
