### ISSUE TITLE
Bug? Occasionally get "unlicensed" dialog

### ISSUE THREAD

**Issue by ope-nz** [RickStrahl/WestWindWebSurge#105]
Hi, I occasionally get the unlicensed dialog showing even though the app is licensed. I havent figured out the pattern that results in this scenario yet.

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/0653ddaa-32ec-456e-92ad-433f09131179)

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/5d0370bb-0b94-4612-badb-5cf617f76958)

**Comment by RickStrahl** [comment]
Are you offline a lot? WebSurge rechecks the license occasionally and if you are often offline. There's a delay and retries over multiple days, but  it will eventually fail if you are not online and invalidate the license.

**Comment by ope-nz** [comment]
Hi Rick, the machine is online 99% of the time. I cant replicate it on demand but for example Ive had this two or three times this morning already (within a space of a couple of hours).

**Comment by ope-nz** [comment]
@RickStrahl , I can replicate this on demand.

Ive got a test that has 16K tests in it (file is approx 5.5Mb). If I double click this test the UI stalls and it shows unregistered once loaded. Im guessing it isnt able to confirm the registration due to the loading of the tests.

If I do the same with a smaller test 1k tests (approx 1Mb) then its fine.

**Comment by ope-nz** [comment]
@RickStrahl FYI also starting to see this in the CLI now. Any idea why the CLI thinks its unregistered when the UI app says it is registered?

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/6968f2cc-ea14-46e6-b0cc-5ebf6e46edc0)

**Comment by ope-nz** [comment]
Oh strange, I noticed in a previous test that there was a file called "Registered.key" in the directory of my batch file. If I copy that to the new test then I dont get an error in the CLI.
