### ISSUE TITLE
Request: Separate query string for GET

### ISSUE THREAD

**Issue by ope-nz** [RickStrahl/WestWindWebSurge#106]
I have a test that uses different query string values against the same url. The method is GET which means the query string is part of the URL. 

The problem with this is that in the test results each request is reported separately as the query string is different. I need these grouped together in the results.

With the POST method I can put the request content in the content panel;

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/a34caee8-98de-4dd3-8a01-64e242d65bd4)

Can you consider an ehancement to allow separation of the query string for GET requests similar to POST?

Something like this?
![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/5b6d2649-432d-4eb5-b6fe-04a02d0bd4ed)

**Comment by ope-nz** [comment]
Example of test results. Even though the first and third requests are to the same endpoint and have the same name/group in the session, the results are reported separately. This isnt an issue with POST as the URL's are then the same.

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/15827117-20de-4097-821b-98fa8f3d4472)

**Comment by RickStrahl** [comment]
No there's not going to be a change in the way the data is stored as it uses a standard HTTP trace format that universally usable.

As for grouping -I don't agree that these should be separate. If you really have separate data, it probably shouldn't be passed as querystring values but as POST data. I understand the issue but that's not how HTTP is supposed to work - each URL is unique including the querystring. That's one reason why data is supposed to go in the POST body and not on the query string.

**Comment by ope-nz** [comment]
No problem RIck, Ive moved the tests to use POST and its doing what I need.
