### ISSUE TITLE
Messagebox in 2.2.23

### ISSUE THREAD

**Issue by ope-nz** [RickStrahl/WestWindWebSurge#108]
There is a messagebox appearing in 2.2.23 after I run a test. 

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/806b59c8-568a-43b1-981f-b256592be0b2)

Oh I did notice there is a sample addin included in the installer and it seems to be coming from there,,,

**Comment by RickStrahl** [comment]
Looks like an addin? Can you check the admins folder and remove any admins there or turn the addin option off in the settings.

**Comment by RickStrahl** [comment]
I’ll check and see if the test addin was accidentally shipped in this release. Thanks

**Comment by RickStrahl** [comment]
Yup the sample addin was accidentally shipped in the distribution. 

I've republished with 2.2.24.
