### ISSUE TITLE
Import swagger does not capture query parameters for GET requests

### ISSUE THREAD

**Issue by FlowWrightCode** [RickStrahl/WestWindWebSurge#109]
does not import query parameters for GET calls

**Comment by RickStrahl** [comment]
Took a look at this finally and we are now importing the query string parameters and appending them to the end of the url in the following format:

```
/api/artists?artistNameFilter={string}
```

You can then decide to remove parameters or create new requests using multiple parameter variations.

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/1374013/8153ad1d-0595-4918-a5da-6db4b62b2099)
