### ISSUE TITLE
Request Timeout is not in Ms

### ISSUE THREAD

**Issue by ztaff** [RickStrahl/WestWindWebSurge#111]
I assume that the label "Request Timeout Ms" means that I should enter value in milliseconds.
Actual timeout is in seconds the number entered in this box.

I have noted it as I am testing a site with continuous load,  that hangs during deployment. 
In the GUI I then get a message in the request inspector "The request was canceled due to the configured HttpClient.Timeout of 50 seconds elapsing.". And I had entered 50 in the "Request Timeout Ms" box.

**Comment by RickStrahl** [comment]
Thank you. Fixed.
