### ISSUE TITLE
Only one hit at login url per thread

### ISSUE THREAD

**Issue by ztaff** [RickStrahl/WestWindWebSurge#112]
As I have understand and set it up with logins for a custom users, I have added the POST url to the list of url:s in the session, and for each custom user I have added a url, same as in the list, with credentials in post body.

As a consequence of this the login page is hit repeatedly during the test, but in real life that page is hit once per user and the the token/cookie is used in all subsequent requests.

It would fantastic to be able to set up for custom users so that the test mimics this behaviour.

All the Best
Staffan

**Comment by RickStrahl** [comment]
That's not how the tests work. Each session is run in sequence and essentially starts new after it's run. Then starts over with the same user from scratch. As such the session should correspond to a user scenario you're trying to test. If that involves multiple passes through URLs you can add the same request multiple times into the session.
