### ISSUE TITLE
Typo - "suceeded" should be "succeeded"

### ISSUE THREAD

**Issue by peaeater** [RickStrahl/WestWindWebSurge#114]
While running a job, the bottom status bar lists the req/sec, number suceeded [sic] and number of failed requests. However, "suceeded" with one c is a misspelling, and should be "succeeded" with two. The word "success" appears to be spelled correctly wherever I see it, though. :)

**Comment by RickStrahl** [comment]
Typo - thank you. Fixed for next update.
