### ISSUE TITLE
Add support for NTLM authentication

### ISSUE THREAD

**Issue by BredStik** [RickStrahl/WestWindWebSurge#14]
Would be great to add support for NTLM authentication since most intranet sites in Microsoft shops use this mode of authentication.  Would gladly submit a pull request, but the required changes need to be made in Westwind.Utilities as far as I can tell.

**Comment by RickStrahl** [comment]
@BredStik - I've added global options for username and password which should allow you to specify a username and password for the request. 

commit 27f2c692af1d714563372ea81ca1822fa1f2a812

It's a bit rough at the moment - password is in plain text and saved with request data as plain text, but please let me know if that works for you.

**Comment by BredStik** [comment]
Am I right in assuming that putting "AUTOLOGIN" as the username without specifying a password will use the executing user credentials over NTLM (as per your HttpClient implementation)?  I used it in my branch and it seems to work fine.

That way, as long as the executing user has access to the site, the password doesn't need to be kept in the request data.

Thanks again for the update.

**Comment by RickStrahl** [comment]
Uh... yes :-) That should work as well.

I will fix the way the password is stored if provided so that it's encrypted.

**Comment by RickStrahl** [comment]
I've updated the password functionality so that the password is encrypted when stored into the config file. The encryption uses an encrypt key based off the machine name so it's not portable across machines.
