### ISSUE TITLE
Very bad performance

### ISSUE THREAD

**Issue by AndersMad** [RickStrahl/WestWindWebSurge#16]
The client (a much faster computer than server) dies before the server reaches its 10% max.. Anything beyond 30 threads makes the client go 100% CPU - WCAT gets 4 x the request/sec by the server..

I suspect that WebSurge tried to unzip/defalte the requests?

**Comment by RickStrahl** [comment]
Hmmm... interesting. I routinely run 100-200 requests getting in the 10-15,000 req/sec range. Granted these are very small requests but still perf shouldn't be this bad.

Make sure you turn off the console (in options) which can improve performance significantly if you have more than a 1000 or so requests/sec. That might also account for the high CPU load.

Note that WebSurge fires requests through a session loop (ie. each thread runs through each full session). If you have one slow request in a session it can significantly slow down the load as it's not just randomly firing requests. This is to more realistically simulate user scenarios that walk through a test but it can result in slow perf as a slow request can significantly slow down the sequence.

I definitely unpack content, parse it and store it, so there will definitely be some overhead in that but again it should not be that markedly high.

One other thing to consider is to make sure that WCAT isn't grabbing cached requests. 

I'll take a look and see if there are any regressions in perf as well. There have been a lot of additions into the pipeline in the latest builds that might have some perf impact.

Thanks for the feedback... 

Let me know whether turning the console view off improves perf for you.

**Comment by RickStrahl** [comment]
@AndersMad Can you take another look at this with the most recent updates? (re-download from http://websurge.west-wind.com/ or grab latest from Chocolatey).

After some investigation I was able to reduce a lot of overhead by tweaking the thread yield code in WebSurge. Modifying this code has resulted in a three-fold increase in request throughput in some scenarios. Using a ms delay of 0 will yield only (no wait at all - previously there was a small delay implied). You can now also use -1 on the request delay option, to have no thread yielding at all. In my tests however the difference between not yielding at all and just yielding is relatively small with the CPU usage slightly better when yielding.

The good news is that we can push a lot more traffic through. The downside is that optimized request load can be very sensitive to the right amount of threads running. Too few and you get too light of a load. Too much and you overload the CPU. In my testing the ideal thread load in these very high performance tests is when the thread count matches the number of CPU cores on the machine. 

The slower requests are, the more additional threads will be beneficial, but with these super fast requests the 10's of thousands of thread switches actually start slowing down tests if there are more than CPU cores.

In comparing against Apache Bench for some local requests against static pages, I see about half of the throughput that AB.exe can deliver which is pretty much what I would expect given that it runs through a higher level .NET stack and performs a bunch of fixup operations. I was able to push my local 8 core i7 laptop to ~45,000 req/sec.

**Comment by AndersMad** [comment]
Hey @RickStrahl, it does seem to work a lot better now! Also it hogs a lot less RAM than before? 

I'd still like an option to just dl the raw content without unzip.. I use CaptureMinRespData = true and MaxResponsiveSize = 10 (I don't care about the result - only the error view with error codes), but that still kills my much faster client because the server is just transmitting cached GZip data.

Btw., pressing stop will sometimes leave some threads executing behind + killing all when pressing stop (when there is a lot of threads) would be nice since e.g. a 1000 threads on slow pages page makes it keep running for a long time.. Cancellation token maybe.

P.S. Off-topic: Could be nice if the ReplaceDomain was not a part of the session data or did not auto load on save. I know it's a bit off - but it's because I often do a side-by-side compare of 2 sites :) Also CTRL + A to select all session lines + then mark active/inactive with another key.. And no need to save request form data - just auto save on edit.. And no websurge-allow.txt tests e.g. on registered versions (it's a pain).. Thanks! ;)

**Comment by RickStrahl** [comment]
@AndersMad Thanks for the feedback.

 I think I can add a flag to not decode content (which is automatic in the client) but my guess the CPU load is not from the result decoding but just the sheer overhead of the threads running (at least that's what I'm seeing).

The websurge-allow.txt isn't so much a 'restriction' feature, but to ensure you can't use WebSurge easily on any site that isn't your's to hammer it with requests. So although I agree 100% that it's a pain, I think it's a necessary thing to avoid using this for evil. Of course there is source so this is easy to remove anyway but still...

**Comment by RickStrahl** [comment]
@AndersMad I've pushed up an update (v0.87.1) that includes a new `NoContentDecompression` option for the session which will cause output to not be gzip decompressed. Curious to see how much this might affect your performance.

**Comment by AndersMad** [comment]
@RickStrahl The `NoContentDecompression` helped - client went from ca. 1k req/s with 100% CPU to 4k req/s using 25% CPU ;)

P.S. Off-topic again: Inactive requests is displayed with a cursive font - really hard to see.. A light gray color would be much better.. If all req is inactive the CPU burns real hot :P

**Comment by RickStrahl** [comment]
Just following up on the off-topic issues:

**ReplaceDomain** is now saved with each session and it will load with the session. I think this is much better than not having it. Either way if you leave it or use somebody is not going to get what they want. I think the more common case is changing and leaving it.

**Ctrl-A** there's no support for Ctrl-A but you can mouse-select all tests and then uncheck selectively.

**websurge-allow.txt** this is not meant as a nuisance but as a security feature to disallow nefarious users from bombing a site they don't own. 

**Inactive Requests** They are just displayed as disabled. If you can't read that then that might be your Windows color or format settings.

Thanks for the feedback.
