### ISSUE TITLE
CheckSite Error: The underlying connection was closed: The message length limit was exceeded.

### ISSUE THREAD

**Issue by stephenpatten** [RickStrahl/WestWindWebSurge#17]
I've created a very simple endpoint in my ServiceStack Service that just logs and echos back your name.

    public class MyServices : Service
    {
        readonly ILog _log = LogManager.GetLogger("LMS.Receiver.Services.Health");

        public object Any(Hello request)
        {
            _log.DebugFormat("Machine:{0} says Hello {1}", Environment.MachineName, request.Name);
            return new HelloResponse { Result = "Hello, {0}!".Fmt(request.Name) };
        }
    }

If I create a Request and have it run for 30 seconds on 10 threads, the error is displayed. Since I'm not using the .NET webrequest object, to the best of my knowledge, I assume you are in the application.

Build 0.87b - 64 bit

Thanks Rick.

**Comment by RickStrahl** [comment]
Any chance I can reach this URL? 

I made a change for optimization in the last build to turn off the default 100Continue behavior. It kind of sounds like the response is a 100 Continue request that might be failing?

IAC, if you have a URL I could hit to duplicate that would be great.

**Comment by stephenpatten** [comment]
DM me on twitter, and I'll try to provide what you need.

**Comment by RickStrahl** [comment]
I've added the Expect 100 support back in, and have updated the downloadables (you can grab the current zip file or `choco install westwindwebsurge -f` to force a reinstall.

I have a feeling this is what the problem is so give this a try and let me know what you find.

**Comment by RickStrahl** [comment]
Doing a little more research: Could it be that you're running out of connections on the server and the server is refusing connections?

http://stackoverflow.com/a/13678178/11197

**Comment by stephenpatten** [comment]
No, it turns out though the answer was on the page, Carlos Mendes recommended turning off MiniProfiler and now I've got a clean run and the requests per second almost doubled.

**Comment by RickStrahl** [comment]
Awesome! Thanks for the heads up!
