### ISSUE TITLE
Program does not consitantly know if the websurge-allow.txt is on the target web server

### ISSUE THREAD

**Issue by stephenpatten** [RickStrahl/WestWindWebSurge#18]
After a couple of runs, the program fails to find the blank text file and so refuses to proceed. Is this a built in way of limiting users who are on the free version?

**Comment by RickStrahl** [comment]
No there are no limits in the free version (other than the nag screens). So this should work.
So are you saying it's working for some requests and then failing after a bit?

Not sure why that would happen. WebSurge is supposed to keep track of each domain it hits in a test and checks for the file on that first hit. After success the domain goes into a static list that's checked. So once verified I'm not sure why it would fail. I can see failures if the file are not there or there's an error accessing the file, but I would assume that would happen immediately. 

I'll take another look at the code....

**Comment by stephenpatten** [comment]
Ahh, I had 2 sites that were not active that did not contain the txt file. Sorry Rick.

**Comment by RickStrahl** [comment]
Hmmm... you're saying it didn't work even though the sites were inactive? If that's the case that's a bug.

**Comment by RickStrahl** [comment]
Fixed bug that checked inactive sites for websurge-allow.txt.
