### ISSUE TITLE
Command line parameter /? crashes WebSurgeCli

### ISSUE THREAD

**Issue by steveculshaw** [RickStrahl/WestWindWebSurge#19]
Tried to get help with the usual /? and get a hard crash from the Cli ...

    c:\Program Files\West Wind WebSurge
    >WebSurgeCli.exe /?

    Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
       at WebSurge.SiteValidator.CheckAllServers(IEnumerable`1 requests)
       at WebSurge.StressTester.CheckAllSites(IEnumerable`1 requests, Int32 threadCount, Int32 seconds, Boolean runOnce)
       at WebSurge.Cli.Program.Main(String[] args)

This is with version 0.87

**Comment by RickStrahl** [comment]
Yes - the command line switches are - delimited - for help though you can use no parameters.

**Comment by steveculshaw** [comment]
Yeah, got the help fine ... it was just old habit that I went for the /? and found the exception / crash

**Comment by RickStrahl** [comment]
Yeah it shouldn't crash - it should give an error that this is an invalid URL or maybe special case the /?

**Comment by RickStrahl** [comment]
Fixed in v0.87.2 along with a couple of other CLI issues. You can redownload or do a forced reinstall from Chocolatey.

**Comment by steveculshaw** [comment]
For me the /? is such a common parameter for a lot of command line app's, I'd make it a special case

**Comment by RickStrahl** [comment]
I understand but I don't want to special case that. You get a message now that it's not a valid Url - no crash. Reason is I already display the help page if you pass no parms and all the parameter parsing using the more common - syntax for all parameters.

**Comment by steveculshaw** [comment]
Oh, completely understand ... just shame we have so many different ways for command line args ... your approach is in keeping with things like curl which seems best choice
