### ISSUE TITLE
Adding POST parameters leads to an error

### ISSUE THREAD

**Issue by toby78** [RickStrahl/WestWindWebSurge#21]
"CheckSite Error: Object reference not set to an instance of an object" appears if POST variables are added in the body, e.g. x=y

**Comment by RickStrahl** [comment]
Can you post your request (modified if it's sensitive).

You shouldn't be getting errors with POST data - it's possible that something else is failing in the request. It might be a header  of some sort that's not handled properly.

To find the request go into the session viewer and use the edit button to edit the session text, then find your request and paste it here. I'd appreciate it.

**Comment by RickStrahl** [comment]
Not enough info to follow up on this. Closing issue.
