### ISSUE TITLE
Allow TLS 1.1 and TLS 1.2

### ISSUE THREAD

**Issue by npiasecki** [RickStrahl/WestWindWebSurge#26]
PCI is supposedly dropping the hammer on TLS 1.0 by June 2016. Dropping TLS 1.0 now breaks all the things, but lots of vendors (like UPS) are planning to go TLS 1.2-only with their services sometime in late 2016. Microsoft added support for this in .NET Framework 4.5, but it isn't turned on by default. To allow the use of TLS 1.1 or TLS 1.2 on .NET Framework 4.5 or later, you have to add a few flags during startup:

ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11;
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;

It'd help out for using the tool to test against services that reflect the "stop using TLS 1.0 in new applications" guidance from PCI. Thanks!

**Comment by RickStrahl** [comment]
Thanks for pointing this out - I wasn't aware that this was explicitly required. are you saying that if you access a TLS 1.1/1.2 site you get a failure? Wouldn't this fail on just about any site then? Hard to test since we disable testing arbitrary sites unless a header or file exists on the server.

**Comment by npiasecki** [comment]
Well, virtually all sites today support TLS 1.0 in addition to 1.1 and 1.2 because most people aren't masochists -- so they just work in the default .NET configuration, which has TLS 1.0 and SSL 3.0 in the mix. But if you try to connect to a server that explicitly disallows TLS 1.0, then the default configuration has nothing left to negotiate with and you end up with a socket exception. 

As an example, you can hit https://api.labels.shipvine.com/ping in a modern browser and you'll get a PONG back under TLS 1.2; but if you hit it under a default .NET configuration such as what the product currently has, you get "An existing connection was forcibly closed by the remote host". Which it was -- the server was saying "no" to list of protocols it was presented with.

So in terms of affecting people today it's like zero. But I just got an e-mail from UPS, for example, saying they're going TLS 1.2 only on May 31st, 2016, in response to the PCI deadline of June 2016. So I think this sort of thing is going to pop up a lot more in the coming months -- the fix is as simple as adding a few extra flags, but I suppose it could also be a plug-in until more people really need it. Thanks for listening!

**Comment by RickStrahl** [comment]
Thanks for the details. I'll get this fixed. Do you have a server you can test with by any chance? I don't have any servers that I control that run TLS 1.2.

**Comment by npiasecki** [comment]
Yep. You can run a single test against  https://api.labels.shipvine.com/ping ... if you get a reply back, it's working. If the server closes the connection, then TLS 1.1 or TLS 1.2 wasn't enabled. The server doesn't allow TLS 1.0.

**Comment by RickStrahl** [comment]
Added. Thanks again for pointing this out!
