### ISSUE TITLE
Handle threads as actuale "web users"

### ISSUE THREAD

**Issue by jaykay-design** [RickStrahl/WestWindWebSurge#30]
Having many threads requesting a server sometime causes issues like session deadlocks when the cookie is pre-set with a session value.
It would be great to handle cookies on a per thread base simulating actual users. 

This feature could be extended to also have separate Auth headers per thread. Good for user based caching tests.

**Comment by djjlewis** [comment]
A client I am working with is currently looking to purchase a different commercial load testing product which is _a lot_ more expensive, even though I believe most of what they need would be achievable with Websurge. However, it does have the ability to import real users from a spreadsheet / csv etc and actually run each VU under those credentials which does help as it helps simulate different loads on the DB (per user queries) and if caching is being used effectively etc.

**Comment by RickStrahl** [comment]
Each session already runs requests on separate threads. It's possible to create an addin to add custom logic to pass forward cookie information and set 'users' for login requests.

I've looked at this on a number of occasions, but frankly I'm having a hard time coming up with a good API and UI for generically managing users. 

Maybe we can start the discussion on how this should work in terms of how users are managed and what they should push into the requests.

**Comment by RickStrahl** [comment]
Closing and moving conversation to #43
