### ISSUE TITLE
Issue with TLS12-only web sites

### ISSUE THREAD

**Issue by MarkEinhorn** [RickStrahl/WestWindWebSurge#31]
Websurge doesn't load websurge-allow.txt or robots.txt @Allow: Websurge if a site has been hardened to use only TLS12 and the default ServicePointManager.SecurityProtocol is not set to SecurityProtocolType.Tls12.

I tested in IsWebSurgeAllowedForUrl(string serverUrl) and added the follow line:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Websurge was then able to connect.

There should be an option to set ServicePointManager.SecurityProtocol within Websurge itself.

**Comment by RickStrahl** [comment]
Hmmm... that was fixed a while back in Issue #26.
