### ISSUE TITLE
TimeTakenSecs and RequestsPerSeconds from --json look wrong

### ISSUE THREAD

**Issue by wasphub** [RickStrahl/WestWindWebSurge#32]
I'm evaluating Web Surge, which looks very interesting. I noticed something wrong, when you use the `--json` flag the `RequestsPerSeconds` property is actually reporting the number of requests per _milllisecond_. Also `TimeTakenSecs` it's actually displaying milliseconds, and this is probably the root cause for `RequestsPerSeconds` being wrong.

**Comment by RickStrahl** [comment]
Will take a look. Not sure why this would show up only in the --json flag since it all runs through the same engine. Do you see the same behavior in the UI?

**Comment by wasphub** [comment]
I did not notice anything strange neither in the UI nor in the output of the command line tool without --json specified. My impression is that all the numbers are in fact correct when you think about them in milliseconds and treat them as such in code, but for some reasons the json structure names them as if they were in seconds. That would explain why in general all looks correct and coherent except for that specific output labels.

**Comment by RickStrahl** [comment]
Can you take another look in 1.4 forward. There have been a number of fixes to normalize the summary values.

**Comment by wasphub** [comment]
Thanks Rick. Not sure I will have time to check in a short time, I moved to a different project in the meantime, but as soon as I get back to something that requires WWWB I'll surely do!
