### ISSUE TITLE
Large Request Count: Request-List not scrolling down to end

### ISSUE THREAD

**Issue by maiersoft** [RickStrahl/WestWindWebSurge#36]
Hi Rick,
i'm experiencing an issue with  session files that contain a large number of requests.
Concretely, the request list in the left pane doesn't allow to scroll down to the last list item, which is always hidden.   It Looks like it's hidden under the Status bar, see screenshot. As a new request always gets saved at the bottom this is becoming an issue as soon as you reach this point.

Thanks,
Joe
![websurgebug](https://cloud.githubusercontent.com/assets/230199/23468110/34ed312a-fea0-11e6-92c2-2b2df97f17b3.PNG)

**Comment by RickStrahl** [comment]
Fixed d547a385dc84fcffe17494eca6da73511cb0f74e

Thank you. Updated with 1.2.1 on the Website.
