### ISSUE TITLE
StressTestForm.RequestData_Changed

### ISSUE THREAD

**Issue by Jon12345** [RickStrahl/WestWindWebSurge#37]
StressTestForm.RequestData_Changed causes an exception if ActiveRequest is null. 

Unfortunately VS Code Analysis doesn't pick this up. I wonder if another static analysis tool would.

**Comment by RickStrahl** [comment]
Fixed.

aadc9a0851dfac13b20fd7b56ae5a4f335bb0b65

Thank you and sorry for the long delay.
