### ISSUE TITLE
CheckSite Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Jon12345** [RickStrahl/WestWindWebSurge#38]
Caused by: HttpRequestData.GetRequestContentBytes() when TextEncoding is null.

**Comment by RickStrahl** [comment]
Sorry for the delay getting to this. Will take a look in the next day or so.

**Comment by RickStrahl** [comment]
Fixed with default content encoding setting. 

c6d6610f1d299a397f3f5eed3e20d10bc004dd74
