### ISSUE TITLE
Parsing JSON response from CLI not possible due to other output

### ISSUE THREAD

**Issue by gregpakes** [RickStrahl/WestWindWebSurge#41]
I am trying to use the CLI in my build/release pipeline.  I am trying to parse the JSON output, but it often fails due to other output from the tool.   I want to submit a PR to solve this, but want to discuss it first.

**Proposal**

- Create a new ErrorMessages array on the JSON output to contain any errors that occurred (grouped to limit size)

Two options:
1. Clear all other output from the tool (console.writeline) so the output can be captured and parsed.
2. Add an option to save the JSON output as a file (leave all other output the same).

**Comment by gregpakes** [comment]
PR #42

**Comment by RickStrahl** [comment]
I see you took route 2. with the external output file and that looks good. I've merged your changes in.

Not sure how to test your scenario exactly.

**Comment by RickStrahl** [comment]
FWIW wouldn't it have been enough to run with the `-y0` switch which surpresses all progress info?

```
websurgecli http://localhost/wconnect/testpage.wwd --json -y0
```

**Comment by gregpakes** [comment]
@RickStrahl 

I actually took both routes.  Sadly, no it wouldn't have been enough.  Exceptions were written to the console as they occurred, therefore ruining the JSON output.

I decided to make the outputFile option just in case you wanted to put the exceptions back.

**Comment by gregpakes** [comment]
@RickStrahl 

> Not sure how to test your scenario exactly.

Start-LoadTest.ps1
```
param
(
	[Parameter(ValueFromRemainingArguments=$true)]
    [string[]]$args
)

$webSurgePath = Join-Path $PSScriptRoot "WebSurge\WebSurgeCli.exe"
$result = & $webSurgePath $args --json --outputFile "output.json"

try
{
	if (Test-Path "output.json")
    {
        $json = Get-Content "output.json" | ConvertFrom-Json
    }else{
        throw "Failed to find output file [output.json]"
    }
}catch{
	# Unable to convert output to JSON
	Write-Host "##vso[task.logissue type=error;]$($_.Exception.Message)"
	throw $_.Exception.Message
}

$json.TestResult


if ($json.TestResult.FailedRequests -gt 0){
    $errorString = "Detected $($json.TestResult.FailedRequests) failed requests"
	Write-Host "##vso[task.logissue type=error;]$errorString"

    # Loop through any error messages
    foreach($errorMsg in $json.TestResult.ErrorMessages)
    {
        Write-Host "##vso[task.logissue type=error;]$($errorMsg.Message) ($($errorMsg.Count))"
    }

	throw $errorString
}
```

**Comment by RickStrahl** [comment]
So I'm kind of confused by what you're seeing. I just created a test session that includes some broken links (ie. errors) and here is the results I get:

![image](https://user-images.githubusercontent.com/1374013/27944876-86f25600-629e-11e7-9a25-a5a3870b8165.png)

Notice it just generates JSON - no message with the `-y0` switch which should be perfectly usable for piping or writing out. 

What am I missing here?

**Comment by gregpakes** [comment]
This is the line I removed to stop the exception output:

https://github.com/RickStrahl/WestWindWebSurge/pull/42/files#diff-494a8c8c75e8ee171847df49005f7c88L367

**Comment by RickStrahl** [comment]
I don't see any messages on failure requests - even with the old version so not sure what triggers that.

IAC - your change is good. So with these changes do you have what you need?

**Comment by gregpakes** [comment]
Yeh - I now have what I need.

I think the issue only occurs when the issue is thrown by the http client (timeout).  If the server responds with a 500 or something similar, it wouldn't drop into the catch from the line I outlined above.

**Comment by RickStrahl** [comment]
Great. Thanks for the feedback and PR!
