### ISSUE TITLE
CheckSite Error: The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by natenho** [RickStrahl/WestWindWebSurge#48]
Even when IgnoreCertificateErrors is enabled for the session, the error still occurs for HTTPS requests.

**Comment by natenho** [comment]
It seems like the following configuration should work, but I could not manage to apply it.

  "StressTester": {
    "IgnoreCertificateErrors": true
  }

**Comment by RickStrahl** [comment]
This setting only affects expired certs, not non-registered or completely unreachable certs. 

Make sure your certs are valid to the machine that is doing the testing (ie. you should be able to open the site in the browser without errors and without having to install a custom cert).
