### ISSUE TITLE
Creating single user does not work

### ISSUE THREAD

**Issue by rajBar** [RickStrahl/WestWindWebSurge#49]
Hello,

I've created an ASP.NET MVC Web App.
Websurge works perfectly when testing a page not required to be logged on to view.

However after amending the JSON to allow a specific user, mine still does not seem to work. 
Have I filled this incorrectly?

```
GET http://localhost:54667/Home/Index HTTP/1.1
Accept-Encoding: gzip,deflate

------------------------------------------------------------------


----- Start WebSurge Options -----

{
  "NoProgressEvents": false,
  "DelayTimeMs": 2,
  "NoContentDecompression": false,
  "CaptureMinimalResponseData": false,
  "MaxResponseSize": 0,
  "ReplaceQueryStringValuePairs": null,
  "ReplaceDomain": null,
  "ReplaceCookieValue": null,
  "ReplaceAuthorization": null,
  "Username": null,
  "Password": null,
  "Users": [
    {
      "LoginUrls": [
        {
          "Url": "http://localhost:54667/Account/Login?ReturnUrl=%2F",
          "Headers": [],
          "FormVariables": [
            {
              "Key": "Email",
              "Value": "admin@admin.com",
              "BinaryValue": null
            },
            {
              "Key": "Password",
              "Value": "Admin!23",
              "BinaryValue": null
            },
            {
              "Key": "RememberMe",
              "Value": "on",
              "BinaryValue": null
            },
            {
              "Key": "LoginButton",
              "Value": "Log in",
              "BinaryValue": null
            }
          ],
          "ContentType": "application/x-www-form-urlencoded",
          "RawContent": null,
          "HttpVerb": "POST"
        }
      ],
      "AuthCookie": null
    }
  ],
  "RandomizeRequests": false,
  "RequestTimeoutMs": 15000,
  "WarmupSeconds": 2,
  "ReloadTemplates": false,
  "FormattedPreviewTheme": "visualstudio",
  "LastThreads": 2,
  "IgnoreCertificateErrors": false,
  "TrackPerSessionCookies": true,
  "LastSecondsToRun": 10
}

// This file was generated by West Wind WebSurge
// Get your free copy at http://websurge.west-wind.com
// to easily test or load test the requests in this file.

----- End WebSurge Options -----


```

I've used the html ID and Name tag values for my key value for each of the elements in my login form.

Note - Rick's example JSON also had the key starting with 'ctl00_Content_' I also tried this and it does not work.

Any suggestions on what I'm doing wrong, or how to fix this issue?

Regards,
  - Raj

**Comment by AstuteMediaDev** [comment]
We're also experiencing this problem with ASP.Net form authentication.

If I run the session via CLI and watch Fiddler I can see no form posts ever occur, it just keeps getting a bunch of 302s.

Will have to look for another load testing solution if we can't get this working :(

**Comment by RickStrahl** [comment]
ASP.NET Forms auth redirects to a login form and so if you're not authenticated you will always be redirected via 302s.

For this to work the login steps have to be part of your test script with cookie tracking enabled OR you can explicitly capture a valid request cookie and assigning it to the the **ReplaceCookieValue** section:

![image](https://user-images.githubusercontent.com/1374013/39646414-376b45c6-4f90-11e8-8b18-1b48c2fc6d55.png)
