### ISSUE TITLE
SiteValidator and UI-Router for AngularJS

### ISSUE THREAD

**Issue by scottiemc7** [RickStrahl/WestWindWebSurge#50]
Hi,

I was recently trying out Web Surge and ran into an issue. When I include any path from my AngularJS SPA, I get an error message telling me I can't run the stress test on the server, and that I need to either put the websurge-allow.txt file in the root or update robots.txt with "#Allow: WebSurge". Web Surge seems to be taking issue with the hash that I have in my url - https://www.awesomeurl.com/application#/dashboard. Looking at WebSurge.Core/SiteValidator.cs, the method that is parsing the root from my url looks like this 

        string GetServerRootUrl(string url)
        {
            // fix up if stress tester is replacing the domain
            if (!string.IsNullOrEmpty(StressTester.Options.ReplaceDomain))
                url = StressTester.ReplaceDomain(url);

            var uri = new Uri(url);            
            var builder = new UriBuilder(uri);            
            
            builder.Path = string.Empty;
            builder.Query = string.Empty;
            return builder.ToString();
        }

For my example url, that returns https://www.awesomeurl.com:443/#/dashboard, which is obviously not the root and so it looks like I'm stuck. Would it make sense to change the last line of GetServerRootUrl to

       //return builder.ToString();
      return builder.Scheme + "://" + builder.Host + ":" + builder.Port + "/";
    }
or something similar?

**Comment by scottiemc7** [comment]
Actually, I'm slowly realizing that this may not be the right tool for a front end heavy website, so there's no actual issue here.

**Comment by RickStrahl** [comment]
I'm going to re-open this since this is definitely a bug.

Interesting that URI and Uri builder get screwed up by the hash bang route in the Url. I'll take a look and see how to fix that - could be done with parsing but it's a little odd that these system classes are essentially choking on this URL.

**Comment by RickStrahl** [comment]
Looks like this will fix with:

```cs
string GetServerRootUrl(string url)
{
	var uri = new Uri(url);
	
	var builder = new UriBuilder(uri);
	builder.Dump();

	builder.Path = string.Empty;
	builder.Query = string.Empty;

    
	var port = ":" + builder.Port;
	if ((builder.Scheme == "https" && builder.Port == 443) ||
		(builder.Scheme == "http" && builder.Port == 80))
		port = "";

	return $"{builder.Scheme}://{builder.Host}{port}";
}
```

**Comment by scottiemc7** [comment]
It is kind of an odd one. Thanks for the fix.
