### ISSUE TITLE
Feature Request  - Pinned requests to be made before all others

### ISSUE THREAD

**Issue by merlin2375** [RickStrahl/WestWindWebSurge#51]
We would appreciate consideration for adding a new feature where certain requests can be "pinned" in the session list. **Pinned items would be executed only once, in order, at the beginning of the session even if the randomize option is turned on.** 

This would allow for rapid testing of a site that requires authentication because a get/post request can be made to sign in the session thread and then all other request can be randomized to simulate a more realistic environment.

Thank you for the consideration.

**Comment by RickStrahl** [comment]
I've added this functionality to 1.12. Fixed in c6d3e54345f87ee44e53f9bab89470f11906b513.
