### ISSUE TITLE
Authentication and robots.txt or websurge-allow.txt

### ISSUE THREAD

**Issue by AstuteMediaDev** [RickStrahl/WestWindWebSurge#52]
Hello all

Just noting a solution we found to this problem in case anyone else encounters the same.

We have a staging server behind the usual ASP.Net forms authentication, which has an exemption based on IP so it will auto login our development machines.

We couldn't get WebSurge to run in test mode for this server.

The problem was that robots.txt (or websurge-allow.txt) were initially behind the authentication, so WebSurge was requesting them and getting a 302 before the auto login, which presumably confused it.

Once we added authorization exemptions for these files testing worked fine.

**Comment by RickStrahl** [comment]
Ah yes - thank you for posting this as a reminder. I'll add it to the documentation.
