### ISSUE TITLE
[I'm a new user] WebSurge can't load session

### ISSUE THREAD

**Issue by andrzejmartyna** [RickStrahl/WestWindWebSurge#53]
Because I'm new I might not know sth fundamental for other users but...

I've got a session from a friend and he said "load it to WebSurge".
I've downloaded the tool (1.9 version which BTW wrongly says that 1.9.1 is available).
I've tried to load it and you see the result on screenshot attached. The session is also attached.

It looks like it thinks that there is only one request in the file and it messes it up with other requests so I cannot do anything with it.

[BodyTypes.websurge.txt](https://github.com/RickStrahl/WestWindWebSurge/files/2031882/BodyTypes.websurge.txt)
<img width="2097" alt="websurge" src="https://user-images.githubusercontent.com/4319685/40437228-158a766e-5eb5-11e8-839d-4f2e6fef1e9a.png">

**Comment by RickStrahl** [comment]
Looks like the problem is that the file was re-encoded  and the original CRLFs were turned into just LF.

To fix open in an editor that supports setting Line Feed format (like VS Code) and change to CRLF and the file should open properly.

This a bug that should be addressed.

**Comment by RickStrahl** [comment]
Fixed b06cc034cbf52570f7fe9c2f49ce2749b8e689eb
