### ISSUE TITLE
Load testing with load balancer cannot find websurge-allow.txt

### ISSUE THREAD

**Issue by alexkwh** [RickStrahl/WestWindWebSurge#55]
Hello,

We have a load balancer set up which redirects request to 2 different servers and we have placed the websurge-allow.txt on both of them.

However the tool kept saying it couldn't find the file, but I can see the file directly from the web browser.

Any help would be great.

Thanks

**Comment by RickStrahl** [comment]
Can you retry with the latest version that came out yesterday?
