### ISSUE TITLE
websurge-allow.txt or robots.txt not detected

### ISSUE THREAD

**Issue by balasakthis** [RickStrahl/WestWindWebSurge#58]
I have hosted my ASP.NET Core Web Application in Digital Ocean in Ubuntu 18.04. I am using **nginx** as a Reverse Proxy Server. I am using a **Self-signed certificate**. 

I placed the robots.txt file as in the below location:
**/ASP.NETWebAppFolder/wwwroot/robots.txt**

I am able to view the contents of robots.txt using a browser.
_https://DigitalOceanHosterIP/robots.txt_

When I start the Load Test using **West Wind WebSurge**, I am getting the below error:
`"Unable to run Load Test at https://ASP.NETWebAppName. ..... or you can.... #Allow: WebSurge...."`

I got the same error, when I added **websurge-allow.txt**. Then, I tried with robots.txt. Still, I am getting the same error.

Should I do any configuration change in **nginx.conf**? Please let me know if I am missing something.

**Comment by RickStrahl** [comment]
Authentication perhaps? The file has to be directly accessible without any special server requirements as only a raw request is sent.

You can test this by adding the URL as one of your URLs in the test run and see what that gives you. If that doesn't not work it won't recognize the file. You can run trace with Fiddler (or other HTTP tool to see what is actually happening on the wire).
