### ISSUE TITLE
Use websurge for Azure FUnction

### ISSUE THREAD

**Issue by riccardobecker** [RickStrahl/WestWindWebSurge#61]
Hi,

i want to use WEbsurge to test an azure function with a http trigger. What is the way to get the websurge-allow.txt available in the Azure FUnction?

thanks in advance
Riccardo

**Comment by riccardobecker** [comment]
All, already found a way to do this by using a proxy. Dont bother anymore, if anyone is interested, let me know, i can post a snippet here.

Thanks

**Comment by RickStrahl** [comment]
P
