### ISSUE TITLE
411 length required

### ISSUE THREAD

**Issue by mirza21** [RickStrahl/WestWindWebSurge#62]
I captured some request from my website. I have a single page application that make ajax call to webapi.
I am getting 411 . Length required error for some POST requests.  Content-Length header is set .I could not figure out what is causing this.

One thing I noticed is that . Only those Post request are failing where I am trying to get data from server. Those request that are submitting data using Post request are succeeding.

Any help how this could be corrected.I am currently evaluating your product and would possibly recommend it for buying to by organization because it is very easy to use . But this case just stopped me from going ahead.

**Comment by RickStrahl** [comment]
I'm not really sure what you're asking here. The `Content-Length` gets set automatically when the request is sent with a POST buffer, so the length is always there **unless you add the content-length yourself**. In that case the length **may be wrong** and that may cause the 411 error.

The short of it is: don't add a content-length to the request manually - let WebSurge add it as it runs and calculates the correct size.

**Comment by marcothz** [comment]
I'm having a similar problem. My POST request doesn't have a body, then I notice WebSurge doesn't send the `Content-Type`, as show in the Wireshark capture below:
```POST /api/provisioning?command=ativar&msisdn=5511987654321&tec=3&type=pos&codplan=SERVICO&agrno=354531012 HTTP/1.1
Accept: */*
Cache-Control: no-cache
Accept-Encoding: gzip, deflate, br
User-Agent: PostmanRuntime/7.25.0
Host: localhost:5000

HTTP/1.1 411 Length Required
Connection: close
Date: Sun, 24 May 2020 18:25:14 GMT
Server: Kestrel
Content-Length: 0```

**Comment by leus** [comment]
This is relevant, POST requests without body are badly formed. Either add Content-Length: 0 or use a proper transfer type encoding (Chunked) which should avoid this error (haven't tested it).

I used the workaround of adding a blank to the body. Thanks for that, very clever :-)
