### ISSUE TITLE
IgnoreCertificateErrors=[True] => CheckSite Error: The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by molekm** [RickStrahl/WestWindWebSurge#68]
Tried to set the ignore certificate option in Session Options and after reset of app, I was still getting the certificate error.

So then I have edited WebSurge.exe.config in Program Files installation path to:
     <servicePointManager
          checkCertificateName="false"
          checkCertificateRevocationList="false"         
      /> 

Nothing worked.

Keeps getting errors when run app on :5001.

Postman works fine with ignore SSL certificate issues.

**Comment by RickStrahl** [comment]
Depends on the type of certificate failure. If it's an unsupported protocol (SSL3 or TLS 1.0) it will fail. 

These settings are controlled by the platform BTW (other than the protocols) - WebSurge allows everything that the platform allows when the flag is set. IOW, I can't really change the behavior even if it made sense in this case.

Take a look with a certificate validation tool to see what the actual invalid cert issue is - or probably better make sure the certificate can be validated on the machine you're testing on.

The most common use case - using a dev certificate that's not locally installed - I believe should work.

**Comment by douglasg14b** [comment]
> The most common use case - using a dev certificate that's not locally installed - I believe should work.

In my case, websurge won't work on any device, for any project that's running off a dev cert. Same error as OP, and same `IgnoreCertificateErrors=[True]`...
