### ISSUE TITLE
Feature Request - Total data in MBs sent/received during a test

### ISSUE THREAD

**Issue by saqibsoftwares** [RickStrahl/WestWindWebSurge#70]
Hi, Thanks for the great tool, can you include total MBs send and total MBs received in test results?

**Comment by RickStrahl** [comment]
Added support for display of Total Bytes Sent and Total Bytes posted to both the GUI summary interface and Console summary display.

**Comment by saqibsoftwares** [comment]
Thanks Rick. Appreciated.
