### ISSUE TITLE
Feature Request: Bypass websurge-allow.txt

### ISSUE THREAD

**Issue by chrpai** [RickStrahl/WestWindWebSurge#73]
It would be nice to have some way of bypassing the websurge-allow.txt check.  Either an advanced setting or a list of approved domains or a intranet domain check or something.  This would prevent me from having to modify IsWebSurgeAllowedForUrl() to always return true.

The use case for me is troubleshooting an internal production API that doesn't have the file and would take days to get a change request approved to deploy one.

**Comment by RickStrahl** [comment]
I get it, but  this flag is there to prevent people from (easily) abusing WebSurge to hit random sites under load, not to make your life harder :smile:. The file requires that people have control of the Web site they are hitting.
