### ISSUE TITLE
works fine in IE,but failed in chrome

### ISSUE THREAD

**Issue by jxchenhui** [RickStrahl/WestWindWebSurge#77]
Hi,works fine in IE,but when open chrome,and visit a https web,for example https:www.baidu.com,it will      have a error NET::ERR_CERT_COMMON_NAME_INVALID,and can not continue,but use Fiddler,it works fine
攻击者可能会试图从 www.baidu.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: www.baidu.com

Issuer: DO_NOT_TRUST_FiddlerRoot

Expires on: 2030年3月19日

Current date: 2020年3月22日

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIDYzCCAsygAwIBAgIQkG6VFDisc5ZMZNVrct0bZzANBgkqhkiG9w0BAQsFADCB
izErMCkGA1UECxMiQ3JlYXRlZCBieSBodHRwOi8vd3d3LmZpZGRsZXIyLmNvbTEh
MB8GA1UECh4YAEQATwBfAE4ATwBUAF8AVABSAFUAUwBUMTkwNwYDVQQDHjAARABP
AF8ATgBPAFQAXwBUAFIAVQBTAFQAXwBGAGkAZABkAGwAZQByAFIAbwBvAHQwHhcN
MTkwMzE5MTYwMDAwWhcNMzAwMzE5MTU1OTU5WjBoMSswKQYDVQQLEyJDcmVhdGVk
IGJ5IGh0dHA6Ly93d3cuZmlkZGxlcjIuY29tMSEwHwYDVQQKHhgARABPAF8ATgBP
AFQAXwBUAFIAVQBTAFQxFjAUBgNVBAMTDXd3dy5iYWlkdS5jb20wgZ8wDQYJKoZI
hvcNAQEBBQADgY0AMIGJAoGBAJ4DHLgXZOpovwPQA/H5CCUJSsQy9VxWrqkI26qZ
CIr/WjasAA76Tvm+yc9qoC9FGCWG1aZyoGBVgtMtsCn2yfrdJINlG5Bq6ioJT5Sa
k+pnd/mls7tHfJyj5lUZ7rX+643hL3Uu2/V5ercMUxBBV198rplsjo6phqNND3pF
kSPBAgMBAAGjgekwgeYwDAYDVR0TAQH/BAIwADATBgNVHSUEDDAKBggrBgEFBQcD
ATCBwAYDVR0BBIG4MIG1gBBohJgI6oawUE8cg92SS8VjoYGOMIGLMSswKQYDVQQL
EyJDcmVhdGVkIGJ5IGh0dHA6Ly93d3cuZmlkZGxlcjIuY29tMSEwHwYDVQQKHhgA
RABPAF8ATgBPAFQAXwBUAFIAVQBTAFQxOTA3BgNVBAMeMABEAE8AXwBOAE8AVABf
AFQAUgBVAFMAVABfAEYAaQBkAGQAbABlAHIAUgBvAG8AdIIQRoVXCy+qG5xMox6h
lgzzNjANBgkqhkiG9w0BAQsFAAOBgQCGqeAT56FbjCVdnNJ57vPOyWTP0rnCHRWU
QIjpcLe2M8V8U9VbEzBl7f4WtEul6e4rIZoyvSei+QhfMK3Ens1PS7jNyQzpE4LZ
TSDBSg81PEDM+v4YI0NgaKRmNW58v7zj3C+O/iQwmGLdqy+e0Mx+SCOuXroD7RF7
68YLJSOt5A==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDjTCCAvagAwIBAgIQRoVXCy+qG5xMox6hlgzzNjANBgkqhkiG9w0BAQsFADCB
izErMCkGA1UECxMiQ3JlYXRlZCBieSBodHRwOi8vd3d3LmZpZGRsZXIyLmNvbTEh
MB8GA1UECh4YAEQATwBfAE4ATwBUAF8AVABSAFUAUwBUMTkwNwYDVQQDHjAARABP
AF8ATgBPAFQAXwBUAFIAVQBTAFQAXwBGAGkAZABkAGwAZQByAFIAbwBvAHQwHhcN
MTkwMzE5MTYwMDAwWhcNMzAwMzE5MTU1OTU5WjCBizErMCkGA1UECxMiQ3JlYXRl
ZCBieSBodHRwOi8vd3d3LmZpZGRsZXIyLmNvbTEhMB8GA1UECh4YAEQATwBfAE4A
TwBUAF8AVABSAFUAUwBUMTkwNwYDVQQDHjAARABPAF8ATgBPAFQAXwBUAFIAVQBT
AFQAXwBGAGkAZABkAGwAZQByAFIAbwBvAHQwgZ8wDQYJKoZIhvcNAQEBBQADgY0A
MIGJAoGBANp+YdlAhE2yevBNzGDi8FSktio9jELYvFzRFC/GZh5vT2CYmEFzS64f
xcmcd1jgviD9bNL8D7oobC17JtXmZByJl4Pfd5wA442/CMY+NI6laTm4016Tw4yd
BlJgBc+Epqm41aN5LkkB7RJFr5g/RFDbYMY/D2y2YGvYLzTdYKOvAgMBAAGjge8w
gewwEgYDVR0TAQH/BAgwBgEB/wIBATATBgNVHSUEDDAKBggrBgEFBQcDATCBwAYD
VR0BBIG4MIG1gBBohJgI6oawUE8cg92SS8VjoYGOMIGLMSswKQYDVQQLEyJDcmVh
dGVkIGJ5IGh0dHA6Ly93d3cuZmlkZGxlcjIuY29tMSEwHwYDVQQKHhgARABPAF8A
TgBPAFQAXwBUAFIAVQBTAFQxOTA3BgNVBAMeMABEAE8AXwBOAE8AVABfAFQAUgBV
AFMAVABfAEYAaQBkAGQAbABlAHIAUgBvAG8AdIIQRoVXCy+qG5xMox6hlgzzNjAN
BgkqhkiG9w0BAQsFAAOBgQAdcQiRuzedxvaPlZRMdnMss5AgK/Wjq4YIjDP/qQrZ
cxmMiK5MnrC7oAPMgcDdCBRX34ml6B4e12plrdltJ+umtKCwbNNqTTWIsYdzCOPd
fJUaYjBphPdLkP0euAtnFapL6BWkA//MspD77EjAnlWTetK3j/sh+glEu0nb21Lw
Bg==
-----END CERTIFICATE-----

**Comment by RickStrahl** [comment]
Unfortunately this is due to security restrictions in Chromium browsers to avoid man-in-the-middle attacks (which is essentially what the Fiddler Proxy is doing).

To work around this the DO_NOT_TRUST_FiddlerRoot  needs to be installed into the Trusted Root store.

More info here. 

Alternately I believe you can also tweak Chromium settings to not block requests in the `config:` section of the browser.

I don't think we should automate this because that does go around the security settings that are explicitly in place.
