### ISSUE TITLE
Ramp up time for threads

### ISSUE THREAD

**Issue by shawndube** [RickStrahl/WestWindWebSurge#79]
Is there a way to ramp up the thread count over time? If not, and its a desired feature, do you have any guidance or ideas on how you might want that to work? I'd like to try and take a swing at getting that working.

Was initially thinking of a setting in SessionOptions for ThreadRampUpSeconds, and ramping that linearly over that interval.

**Comment by RickStrahl** [comment]
I'm not sure if that's really a common scenario that needs to be tested. I realize some real world testing scenarios want to mimic traffic patterns, but WebSurge isn't really meant to simulate load patterns but rather meant to test for peak or consistent load scenarios - there's no infrastructure at the moment for thread throttling.

**Comment by shawndube** [comment]
Np. I appreciate the quick response!
