### ISSUE TITLE
Question: Can we import swagger.json?

### ISSUE THREAD

**Issue by StevenTCramer** [RickStrahl/WestWindWebSurge#80]
Hi Rick,  Just saw a screenshot of this tool on your blog post today.  Thought I would check it out.  Was wondering if I could import swagger.json from APIs to quickly get all the endpoints.

**Comment by RickStrahl** [comment]
No support currently, but something I've been thinking about adding.

I'm in the middle of a rewrite of WebSurge, so this is one of the items on the list. May add it to the current version though as the new version will be a while away.

**Comment by RickStrahl** [comment]
Finally getting around to adding this to v2 now.

**Comment by RickStrahl** [comment]
So here's what this looks like at this point:

![image](https://user-images.githubusercontent.com/1374013/144141253-3bac34bb-5b45-4aff-93dc-9cab837aabc2.png)

The import looks something like this:

![image](https://user-images.githubusercontent.com/1374013/144141489-d4d3ef9a-1263-4f0a-946a-a5ef22dad64e.png)


The UI for this is still a little rough but it's now in 2.0.0.22 and later. Imports also may need some work especially for nested object imports, but it's a start.

Going to need to look at some services to be able to test different scenarios.

**Comment by RickStrahl** [comment]
Here's some more detail on the feature:

![SwaggerImport](https://user-images.githubusercontent.com/1374013/146072417-556d817e-6c55-4a6b-b0ff-6cd95b361f99.gif)
