### ISSUE TITLE
Problems installing and running with only User permissions

### ISSUE THREAD

**Issue by adford69** [RickStrahl/WestWindWebSurge#85]
I'm not sure this is even worth your time. But I like your WebSurge tool. So, here's an odd use case if you're ever bored and looking for a challenge.  At the company I work for, software developers only have local User permissions - we do not have local Administrator permissions on our work dev box. In my opinion, this is stupid and creates some serious wastes of time (like this one :-).

Steps:

- I tried to install WebSurge 1.24 64-bit on my Windows 10 computer with User permissions. It failed (didn't write down the error message). 
- I ran the install using "Run as Administrator", entering the credentials we are allowed to "use for installs on our local box" and the installation completed without any error messages.  Sadly, our admin account doesn't have all the other permissions we need to do our software development work, access source repositories, etc (yes it's stupid).
- I tried launching the application with standard User permissions and got a dialog with a title of "WebSurge: Missing Installation Files" and a message "You are missing part of WebSurge's installation files and the application cannot start.  Please run the WebSurge Installer to install or re-install the application and ensure that the template files are created in the required user folder ...."
- I tried launching the application using "Run as Administrator" and entering the same credentials as before. I came up without any errors. But I quickly realized some things don't work right.  For instance, if I try to load a session file saved on my desktop, it looks at the desktop of the Admin user - not mine (this is understandable).
- I tried using Capture and it didn't see my running applications.  So I used "Run as Administrator" to launch Chrome and saw that the capture window started logging requests.  However, Chrome gave the me the show stopper message "Your connection is not private" because it doesn't trust the SSL cert that's being created on the fly. I tried using the Uninstall SSL Fiddler Certificate and the Install SSL Fiddler Certificate but didn't get it to work.  I suspect I can find a way to manually fix this using CertMgr but I'm not sure I want to leave those certs in there permanently.  I like the idea of them being installed when needed and then removed (assuming that's what normally happens).
- I closed WebSurge and copied the C:\Users\xxxx\AppData\Roaming\West Wind WebSurge\html folder from my admin user to my non-admin user.
- I launched WebSurge (without using Run as Administrator).  The app started successfully. I was able to use the Capture feature. But the root/intermediate certs are not quite right so chrome still gives me the "Your connection is not private" message and there's no way around it in chrome.

Since I'm this far, I'm going to see if I can resolve the root/intermediate cert issue.

For comparison, I also downloaded the current Fiddler Classic.  The install worked without using Run as Administrator and it didn't prompt me to enter my credentials either.  I was able to launch Fiddler Classic without using Run as Administrator and it instantly started capturing all my web browser traffic. And the dynamic SSL certs worked too.  I don't know how the Fiddler devs got everything to work with only User permissions.  But it seems like it must be possible.  NOTE: For full disclosure, it's possible that I installed an older fiddler version using Run As Administrator because there was an older version on my computer.

If I were in your shoes, I wouldn't bother trying to solve this use case.  But if you get bored some day and want a challenge, I figured I'd take the time to submit the issue :-).

Thanks!

Aaron

PS.  If I figure out the SSL certificate issue, I'll see if I can update this issue with notes for the work around.

**Comment by adford69** [comment]
I got Capture working for my normal User account and for the Admin account:

- I followed your instructions to "Clear cached RSA Certificates" for the user of the special local admin user. https://github.com/RickStrahl/WestWindWebSurge/wiki/Capturing-SSL-Requests-with-the-Url-Capture-Form
- I logged into my workstation using the local admin user (the one that doesn't give me access to everything else I need).
- I launched WinSurge, opened the Capture option and clicked the option to installed the SSL Cert.  This time I got prompted to trust the Fiddler Root cert (this was new) so I accepted it.
- I started the Capture session and discovered things are now working as expected.  Google.com still gives me the "Your connection is not private" error.  But for non-HSTS websites, I get the same message but the Advanced option in Chrome allows me to continue to the website.  So, that works as expected per the limitations noted in the docs.
- I logged into my workstation using my standard User account and discovered that I can now use Capture there too (with using the Run As Administrator feature).

I suspect that things would have been fine, if I had used the following steps:

- Login to my computer using my "local admin" user
- Install WinSurge
- Run WinSurge, click the Capture option and use the Install SSL Fiddler Certificate option.  When prompted, install the fiddler root cert.  I'm 90% sure I didn't get prompted when I did the original install using the Run as Administrator option.
- Exit WinSurge and copy the C:\Users\xxxx\AppData\Roaming\West Wind WebSurge\html\ folder to the corresponding folder of my User account.

Another interesting observation...  Fiddler Classic will capture my google.com requests despite google using HSTS. It makes me curious if Fiddler Classic is using more full featured logic that the FiddlerCore library provides or if FiddlerClassic is just doing more checks & extra logic than the FiddlerCore team shows in their demo.cs file.

**Comment by RickStrahl** [comment]
WebSurge 2.0 will drop the fiddler capture for an in-application capture browser window so the admin requirement for certificate registration s going away.  Fiddler and it's proxy and cert management has been a pain to maintain, so this was high on my list of things to change.

A preview of 2.0 is now available from the download site (click the Preview link).  

The rest of the application should now be able to run without any special permissions. it's also running on .NET 6.0 so there are some nice perf and system load improvements especially for the test runs.
