### ISSUE TITLE
Request Preview: Formatted html very slow

### ISSUE THREAD

**Issue by AndersMad** [RickStrahl/WestWindWebSurge#86]
On large requests the formatted html is very slow and freezes the app for a long time. "Raw Response" should be the default or a settings. Clicking "Raw Response" wont persist.

**Comment by RickStrahl** [comment]
How big is your HTML?

This is fixed in v2 - as we're using a different HTML control that runs in the background and won't lock the UI while updating. v2 is now in Preview maybe take a look and try that instead.
