### ISSUE TITLE
Some suggestions - Bulk delete request, remember last folder, 

### ISSUE THREAD

**Issue by KamilZm** [RickStrahl/WestWindWebSurge#87]
Hi Rick,
I am trying to use your Websurge 2.0.0.18 and I have some suggestions.

1) I cant bulk delete requests. When I select all requests and press DEL/Shift+DEL or menu Requests/Delete request, the only first request is deleted. It is OK?

2) The application does not remember the last folder. IT is very annoying to change folder every time I would like to save or open a session.

I can't achieve to insert requests from the clipboard. I have tried many format and I have alse tried copy request  from the application saved file but but i was not succesful - nothing happened. How is proper format to import many requests from the clipboard?

Thak you in advance.

Kamil

**Comment by RickStrahl** [comment]
The sticky last folder for sessions has been fixed already. The multi-item delete is supposed to work. I'll take a look.

**Comment by RickStrahl** [comment]
Both of these have been fixed and updated in 2.0.0.19

**Comment by KamilZm** [comment]
Thanks!
May I have a question please? Is there any limit of requests in session? I tried to load session with 10k requests (I edited the save file and added requests) but aplication stucks. If I tried to load a session with 3k request then it works but the application is very slow a every click had very long response time. 
I have Core i9-9900K with 64 GB RAM.

**Comment by RickStrahl** [comment]
10k requests? Wow - never thought about that scenario. 

There's no limit but I suspect the issue might be UI updates of loading and updating the list. Give this another try in the next update as I added virtual scrolling which should improve loading of the list.

Please post as a new issue - let's keep focus to one thing at a time.

**Comment by RickStrahl** [comment]
Just double checked in the latest build:

* Created 20k requests in file
* Opened file in WebSurge

Load time is not instant as is with small files but maybe 2-3 seconds. Navigated around within the list, ran a few requests, deleted a few etc. All seems normal. Ran a load test for a few minutes - also works as expected.

**Comment by KamilZm** [comment]
I have downloaded the latest version 2.0.0.22 and it works very fast. I can load a session with 60k requests now without any problem. Thank you!
I need many requests because I want to test my autocomplete handler and I need many varied values in a URL parameter and I didn't figure out a better way how to achieve it. 
There is still the bug with the last folder for sessions because the function "Save as" remember it but the function "Open session" does not.
