### ISSUE TITLE
https://yahoo.com shows 404 error

### ISSUE THREAD

**Issue by abukres** [RickStrahl/WestWindWebSurge#88]
I tried yahoo.com and it shows 404 not found error.

![websurge](https://user-images.githubusercontent.com/6255956/143999477-59feebb9-40c3-49b7-ab40-dc87be8749a8.gif)

**Comment by RickStrahl** [comment]
You need to provide additional headers: `User-Agent` and `Accept`.

![image](https://user-images.githubusercontent.com/1374013/144001114-4a3d1930-bb3b-4a2a-a5a9-3cb9fb10a408.png)

These big services try to reject all sorts of traffic based on browser and feature sniffing.

For HTML services I would recommend capturing requests with the Request capture tool - that'll ensure the right headers and negotiation occurs.

**Comment by RickStrahl** [comment]
I've also added a User-Agent session configuration setting so you can provide a User-Agent for all requests.
