### ISSUE TITLE
WebSurge.exe run error

### ISSUE THREAD

**Issue by mogaozq** [RickStrahl/WestWindWebSurge#90]
I can't run version 2 of the application. This is the error:

![image](https://user-images.githubusercontent.com/24555665/147579095-447bc07a-6b92-4173-86c0-925a7385cbf8.png)

After clicking **Yes**, it opens the browser with [this link](https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=6.0.0&arch=x64&rid=win10-x64&gui=true)
redirecting to [another link](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime).
I installed .Net Runtime 6.0.0 but the same error comes up again.

this is my recently installed apps:
![image](https://user-images.githubusercontent.com/24555665/147579492-bf3d7d2b-d9a9-40fd-8c53-453282a224d7.png)

------------------
My System Information
------------------
      Time of this report: 12/28/2021, 18:36:25
         Operating System: Windows 11 Enterprise 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)
                 Language: English (Regional Setting: English)
      System Manufacturer: ASUSTeK COMPUTER INC.
             System Model: N552VX
                     BIOS: N552VX.207 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 CPUs), ~2.6GHz
                   Memory: 8192MB RAM
      Available OS Memory: 7608MB RAM
                Page File: 9218MB used, 3765MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12

**Comment by RickStrahl** [comment]
You need the .NET 6.0 **Desktop Runtime** not just the standard runtime.

The Desktop runtime includes the required Windows bindings. There's a link on the [download page](https://websurge.west-wind.com/download) or you can install through Chocolatey which will install the runtime dependency if needed.
