### ISSUE TITLE
Stuck at Warming up Http Pipeline..

### ISSUE THREAD

**Issue by Darwish98** [RickStrahl/WestWindWebSurge#94]
So when I press run it works perfectly. But when I start load testing it gets stuck on "Warming up Http Pipeline.." and then the time is over. What could be the issue?

**Comment by RickStrahl** [comment]
It sounds like the test run time is too short? How many seconds is your test set to run in the text box above?

**Comment by Darwish98** [comment]
Thank you! that solved the issue.
