### ISSUE TITLE
10 Threads 1 User?

### ISSUE THREAD

**Issue by AndersMad** [RickStrahl/WestWindWebSurge#98]
To test concurrency on a single session etc. - is it/could it be possible to set a maximum amout of sessions? It looks like its only possible to have sessions count = thread count. I tried adding a few users, but that doesn't seem to help.

P.S. had a v2.0.x installed and the check for new version said it was the latest - but there was a v2.1.x

**Comment by RickStrahl** [comment]
Not sure I understand what you mean.

You can create x number of sessions with the thread count, but you can have fewer users. The users will spread out over the number of sessions (ie. if you 10 users and 25 threads, each user will be using 2 or 3 sessions to fill those 25 sessions. If you have more users than threads, then only the number of threads/sessions is used from the list of users.

**Comment by RickStrahl** [comment]
Just as a side note:

1 session equals 1 thread, but within the session the actual requests are fired asynchronously (in order though). The thread simply controls the order of the sequence and waits for the session to complete before running the next batch of requests for the session.

Users are mapped to available sessions.

**Comment by AndersMad** [comment]
Its not about user (just mentioned that I have tried with them), its about sessions vs. threads. So each thread has a session (iva cookie), but it could be nice to simulate more than one thread per session. So basically a max number of sessions property.

I ran it in another way - just close it if you dont like the feature.

**Comment by RickStrahl** [comment]
I still have no idea what you're trying to get at by

_but it could be nice to simulate more than one thread per session_

Since the request run asynchronously there are potentially more than 1 thread session depending on the HTTP pool of connections available for all requests running in the test.
