### ISSUE TITLE
 WebSurge-Allow.txt improvements

### ISSUE THREAD

**Issue by reponemec** [RickStrahl/WestWindWebSurge#99]
I'm afraid the measure with WebSurge-Allow.txt is not enough. It is available not only for the application under test, but for all possible applications on that site.
Second, at the time of testing, the site is vulnerable to external attackers. Please consider something like putting some key(s) in this file and the same key in the session.

**Comment by RickStrahl** [comment]
No offense, but this is a ridiculous request. 

It's not like this prevents DDOS attacks in general, which are infinitely more likely to occur than any random hacker using **WebSurge** against your Web site while you are also testing and have explicitly placed a `websurge-allow.txt` on the site.
